### ISSUE TITLE
[Docs] 화면설계서를 작성한다

### ISSUE THREAD

**Issue by Jiyun-Parkk** [EASYPEACH/shroop#7]
## 서비스페이지
- [x] 회원가입
- [x] 로그인
- [x] 마이페이지
- [x] 회원정보 수정페이지
- [x] 메인페이지
- [x] 상품전체리스트 페이지
- [x] 상품 상세페이지
- [x] 상품 등록 페이지
- [x] 상품 수정 페이지
- [x] 상품 거래 페이지
- [x] 중재신청 페이지
- [x] 사기피해 신고신청 페이지

## 관리자 페이지
- [x] 사용자관리
- [x] 상품 관리
- [x] 신고내역관리
- [x] 중재신청 관리

**Comment by Jiyun-Parkk** [comment]
> @Jiyun-Parkk 관리자 페이지까지 마무리했습니다. 확인 부탁드려요!
고생많으셨습니다! 리뷰 남겼습니다~!
https://miro.com/app/board/uXjVMvlW35I=/

**Comment by xotlr333** [comment]
리뷰 작성했습니다~
확인 부탁드립니다!
